install.packages("plyr")
install.packages("dplyr")
install.packages("data.table")
install.packages("stringr")
install.packages("zoo")
install.packages("ggvis")
install.packages("lattice")
install.packages("ggplot2")
install.packages("caret")
install.packages("smotefamily")
install.packages("rpart")
install.packages("RWeka")


library("plyr")
library("dplyr")
library("data.table")
library("stringr")
library("zoo")
library("ggvis")
library("lattice")
library("ggplot2")
library("caret")
library("smotefamily")
library("RWeka")
library("rpart")